"""
2026

UMLS-JKG converter script

Converts the set of 12 "UMLS ontology CSVs" generated by the
UBKG source framework into a JSON that conforms to the JSON Knowledge
Graph (JKG) schema.

"""

import os
import sys

# Import UBKG utilities which is in a directory that is at the same level as the script directory.
# Go "up and over" for an absolute path.
fpath = os.path.dirname(os.getcwd())
fpath = os.path.join(fpath, 'ubkg_utilities')
sys.path.append(fpath)
import ubkg_config as uconfig
import ubkg_logging as ulog
# -----------------------------

def main():
    ulog.print_and_logger_info('umls-jkg')

if __name__ == "__main__":
    main()