#!/usr/bin/env python
"""
2026
ingest_sab.py

ingest_sab.py is the foundation of the UBKG-JKG generation framework.

The framework is a set of ETL subprocesses that obtain information from multiple
source formats, including
- OWL files
- spreadsheets
- downloads from websites and APIs

ETLs are configured via the sab.json file.
"""

import os
import time
from datetime import timedelta
import json
from typing import List
import argparse

from ubkg_utilities.find_repo_root import find_repo_root

# Logging module
from ubkg_utilities.ubkg_logging import UbkgLogging
# argparser
from ubkg_utilities.ubkg_args import RawTextArgumentDefaultsHelpFormatter

# config file
from ubkg_utilities.ubkg_config import ubkgConfigParser

# Subprocess handling
import ubkg_utilities.ubkg_subprocess as usub

#----------------------------------

def getargs() -> argparse.Namespace:
    """
    Obtains command line arguments.
    :return: parsed command line arguments
    """
    parser = argparse.ArgumentParser(
        description='Extract source files and transform to JKG format',
        formatter_class=RawTextArgumentDefaultsHelpFormatter)

    # Multiple SABs can be ingested as a space-delimited list.
    parser.add_argument('sabs', nargs='*', help='space-delimited list of SABs')

    # If -f is specified, obtain a fresh copy of the source files; otherwise,
    # use the stored version.
    parser.add_argument("-f", "--fetch", action="store_true",
                        help='fetch fresh copy of source files')

    args = parser.parse_args()

    return args

def getsabjson(cfg: ubkgConfigParser, ulog:UbkgLogging, repo_root: str, sab_names:list)->dict:
    """
    Reads and validates the sabs.json execution configuration file.
    :param cfg: application configuration
    :param ulog: centralized Ubkg logger
    :param repo_root: repository root
    :param sab_names: SAB names (from runtime arguments)
    :return: contents of the sabs.json file as dictionary

    """
    # Locate the sabs JSON file in the repo.

    sab_json_file = os.path.join(repo_root, cfg.get_value(section='sabs', key='sab_json_file'))

    ulog.print_and_logger_info(f'Reading and validating SAB json file: {sab_json_file}')
    # Read the sabs.json file.
    try:
        with open(sab_json_file, 'r') as f:
            sab_json = json.load(f)
    except FileNotFoundError:
        ulog.print_and_logger_info(f'{sab_json_file} not found.')
        exit(1)

    # Validate keys and values in the JSON.
    valid_keys: List[str] = cfg.get_value(section='sabs', key='sab_json_keys')
    for key, value in sab_json.items():
        if not key.isupper():
            ulog.print_and_logger_info(f'SAB {key} must be upper case.')
            exit(1)
        for key_o in value:
            if key_o not in valid_keys:
                ulog.print_and_logger_error(f'SAB {key}: {key_o} must be one of: {", ".join(valid_keys)}')
                exit(1)

    # Validate the SABs from the runtime line argument against the sabs.json file.
    missing_sab = False
    if len(sab_names) == 0:
        ulog.print_and_logger_error('No SABs provided in runtime arguments.')
        missing_sab = True
    for sab in sab_names:
        if sab not in sab_json:
            ulog.print_and_logger_error(f'SAB {sab} not found in sabs.json')
            missing_sab = True

    if missing_sab:
        exit(1)

    ulog.print_and_logger_info('SAB json file is valid.')
    return sab_json


def fix_owlnets_metadata_file(repo_root: str, cfg: ubkgConfigParser, ulog: UbkgLogging, owlnets_dir: str) -> None:
    """
    Fix files that have tabs in the descriptions and therefore broken records (while saving the original file)...
    :param owlnets_dir: location of OWLNETS files generated by PheKnowlator
    :param cfg: application configuration
    :param ulog: centralized Ubkg logger
    :param repo_root: repository root
    :return:
    """
    owlnets_metadata_file: str = os.path.join(owlnets_dir, 'OWLNETS_node_metadata.txt')
    owlnets_metadata_orig_file: str = os.path.join(owlnets_dir, 'OWLNETS_node_metadata_orig.txt')
    usub.call_subprocess(f"mv {owlnets_metadata_file} {owlnets_metadata_orig_file}")

    fix_owlnets_metadata_file_py = os.path.join(repo_root,cfg.get_value(section='owlnets',key='fix_owlnets_tsv_script_py'))
    fix_owlnets_tsv_script: str = f"{fix_owlnets_metadata_file_py} --fix {owlnets_metadata_file} {owlnets_metadata_orig_file}"
    ulog.print_and_logger_info(f"Running: {fix_owlnets_tsv_script}")
    usub.call_subprocess(fix_owlnets_tsv_script)

def run_pheknowlator_for_sab(cfg: ubkgConfigParser, ulog: UbkgLogging, sab_source_dir: str, sab_jkg_dir: str, sab_json:dict, sab: str, repo_root: str) -> None:
    """
    Call PheKnowlator-related (OWLNETS) scripts to convert OWL files to JKG format.
    :param cfg: application configuration
    :param ulog: centralized Ubkg logger
    :param sab_source_dir: directory for downloaded OWL files
    :param sab_jkg_dir: directory for converted OWL files
    :param sab: SAB
    :param repo_root: repository root
    :param sab_json: SAB execution-specific information from sabs.json file
    :return:
    """

    ulog.print_and_logger_info(f'OWL dir: {os.path.join(sab_source_dir,sab)}')
    ulog.print_and_logger_info(f'JKG dir: {os.path.join(sab_jkg_dir,sab)}')

    # Obtain absolute path to OWLTools directory.
    owltools_dir = os.path.join(repo_root,cfg.get_value(section='directories',key='owltools_dir'))
    ulog.print_and_logger_info(f'owltools_dir: {owltools_dir}')

    sab_config = sab_json[sab]
    owl_url = sab_config['owl_url']
    ulog.print_and_logger_info(f"Processing OWL file: {owl_url}")

    # Pass runtime arguments to the OWLNETS script.
    owlnets_script_py: str = os.path.join(repo_root, cfg.get_value(section='owlnets',key='owlnets_script_py'))
    owlnets_script: str = (f"{owlnets_script_py} "
                           f"--ignore_owl_md5 "
                           f"--clean "
                           f"--verbose "
                           f"--force_owl_download "
                           f"--with_imports "
                           f"--owlnets_dir {sab_jkg_dir} "
                           f"--owltools_dir {owltools_dir} "
                           f"--owl_dir {sab_source_dir} "
                           f" {owl_url} {sab}")
    ulog.print_and_logger_info(f"Running: {owlnets_script}")
    usub.call_subprocess(owlnets_script)


def main():

    # Locate the root directory of the repository for absolute
    # file paths.
    repo_root = find_repo_root()
    log_dir = os.path.join(repo_root, 'generation_framework/builds/logs')

    # Set up centralized logging.
    ulog = UbkgLogging(log_dir=log_dir, log_file='ubkg.log')

    ulog.print_and_logger_info('-' * 50)

    # Obtain command line arguments.
    args = getargs()
    ulog.print_and_logger_info('Command line arguments:')
    sab_names = [s.upper() for s in args.sabs]
    ulog.print_and_logger_info(f' - SABs: {', '.join(sab_names)}')
    ulog.print_and_logger_info(f' - fetch fresh copies: {args.fetch}')

    # Obtain application configuration.
    ulog.print_and_logger_info('Getting application configuration...')
    cfg = ubkgConfigParser(path='ingest_sab.ini', log_dir=log_dir, log_file='ubkg.log')

    # Read and validate the file of SAB-specific configuration.
    sab_json = getsabjson(cfg=cfg, ulog=ulog, repo_root=repo_root, sab_names=sab_names)

    # Process SABs.
    start_time = time.time()
    ulog.print_and_logger_info('-' * 50)
    ulog.print_and_logger_info(f"Processing SABs: {', '.join(sab_names)}")

    # For each SAB, execute the associated ETL subprocess.
    for sab_name in sab_names:

        ulog.print_and_logger_info(f"SAB: {sab_name}")
        source_type = sab_json[sab_name]['source_type']

        # Obtain absolute paths in repo to which to store:
        # - source files for the SAB
        # - converted files for the SAB
        sab_source_dir = os.path.join(repo_root, cfg.get_value(section='directories', key='sab_source_dir'))
        sab_jkg_dir = os.path.join(repo_root, cfg.get_value(section='directories', key='sab_jkg_dir'))

        if source_type == 'owl':
            if args.fetch:
                # Use PheKnowLator to convert OWL files to OWLNETS files.
                run_pheknowlator_for_sab(cfg=cfg,
                                         ulog=ulog,
                                         sab_source_dir=sab_source_dir,
                                         sab_jkg_dir=sab_jkg_dir,
                                         sab_json=sab_json,
                                         sab=sab_name,
                                         repo_root=repo_root)

                owlnets_dir: str = os.path.join(sab_jkg_dir, sab_name)
                fix_owlnets_metadata_file(repo_root=repo_root,
                                          ulog=ulog,
                                          owlnets_dir=owlnets_dir,
                                          cfg=cfg)

        elif source_type in ['simpleknowledge',
                             'ubkg_edge_node',
                             'hra_do',
                             'cedar_entity',
                             'ftu2d',
                             'gencode']:
            # Pass the value of the --fetchnew argument to the subprocess.
            farg = ''
            if args.fetch:
                farg = '--fetchnew'

            script: str = f'{sab_json[sab_name]['execute']} {farg}'
            ulog.print_and_logger_info(f"Running: {script}")
            usub.call_subprocess(script)

        # Add log entry for how long it took to do the processing...
        elapsed_time = time.time() - start_time
        ulog.print_and_logger_info(f'Done! Total Elapsed time {"{:0>8}".format(str(timedelta(seconds=elapsed_time)))}')


if __name__ == "__main__":
    main()