#!/usr/bin/env python
"""
2026
sab2edgenode.py

sab2edgenode.py is the foundation of the UBKG-JKG generation framework.

The framework is a set of ETL subprocesses (translators) that obtain information from multiple
source formats, including
- OWL files
- spreadsheets
- downloads from websites and APIs

Translators are configured via the sources.json file.
"""

import os
import time
from datetime import timedelta
import json
from typing import List
import argparse

# Logging module
from utilities.classes.ubkg_logging import ubkgLogging
# argparser
from utilities.classes.ubkg_args import RawTextArgumentDefaultsHelpFormatter
# Config file
from utilities.classes.ubkg_config import ubkgConfigParser
# sources.json handling
from utilities.classes.ubkg_sources import ubkgSources

# Subprocess handling
import utilities.functions.ubkg_subprocess as usub
from utilities.functions.find_repo_root import find_repo_root

#----------------------------------

def get_args() -> argparse.Namespace:
    """
    Obtains command line arguments.
    :return: parsed command line arguments
    """
    parser = argparse.ArgumentParser(
        description='Extract source files and transform to edge/node format',
        formatter_class=RawTextArgumentDefaultsHelpFormatter)

    # Multiple SABs can be ingested as a space-delimited list.
    parser.add_argument('sabs', nargs='*', help='space-delimited list of SABs')

    # If -f is specified, obtain a fresh copy of the source files; otherwise,
    # use the stored version.
    parser.add_argument("-f", "--fetch", action="store_true",
                        help='fetch fresh copy of source files')

    args = parser.parse_args()

    return args

def fix_owlnets_metadata_file(repo_root: str, cfg: ubkgConfigParser, ulog: ubkgLogging, owlnets_dir: str) -> None:
    """
    Fix files that have tabs in the descriptions and therefore broken records (while saving the original file).
    :param owlnets_dir: location of OWLNETS files generated by PheKnowlator
    :param cfg: application configuration
    :param ulog: centralized Ubkg logger
    :param repo_root: repository root
    :return:
    """
    owlnets_metadata_file: str = os.path.join(owlnets_dir, 'OWLNETS_node_metadata.txt')
    owlnets_metadata_orig_file: str = os.path.join(owlnets_dir, 'OWLNETS_node_metadata_orig.txt')
    usub.call_subprocess(f"mv {owlnets_metadata_file} {owlnets_metadata_orig_file}")

    fix_owlnets_metadata_file_py = os.path.join(repo_root,cfg.get_value(section='owlnets',key='fix_owlnets_tsv_script_py'))
    fix_owlnets_tsv_script: str = f"{fix_owlnets_metadata_file_py} --fix {owlnets_metadata_file} {owlnets_metadata_orig_file}"
    ulog.print_and_logger_info(f"Running: {fix_owlnets_tsv_script}")
    usub.call_subprocess(fix_owlnets_tsv_script)

def run_pheknowlator_for_sab(cfg: ubkgConfigParser, ulog: ubkgLogging,
                             sab_source_dir: str, sab_jkg_dir: str,
                             sab_json:dict, sab: str,
                             repo_root: str, fetch: bool=True) -> None:
    """
    Call PheKnowlator-related (OWLNETS) scripts to convert OWL files to JKG format.

    :param cfg: application configuration
    :param ulog: centralized Ubkg logger
    :param sab_source_dir: directory for downloaded OWL files
    :param sab_jkg_dir: directory for converted OWL files
    :param sab: SAB
    :param repo_root: repository root, used for absolute file references
    :param sab_json: SAB execution-specific information from sabs.json file
    :param fetch: whether to download fresh copy of source files
    :return:
    """

    ulog.print_and_logger_info(f'OWL dir: {os.path.join(sab_source_dir,sab)}')
    ulog.print_and_logger_info(f'JKG dir: {os.path.join(sab_jkg_dir,sab)}')

    # Obtain absolute path to OWLTools directory.
    owltools_dir = os.path.join(repo_root,cfg.get_value(section='directories',key='owltools_dir'))
    ulog.print_and_logger_info(f'owltools_dir: {owltools_dir}')

    sab_config = sab_json[sab]
    owl_url = sab_config['owl_url']
    #ulog.print_and_logger_info(f"Processing OWL file: {owl_url}")

    # Pass runtime arguments to the OWLNETS script.
    # Assume that the OWL file has no imports.
    owlnets_script_py: str = os.path.join(repo_root, cfg.get_value(section='owlnets',key='owlnets_script_py'))

    force_owl_download = ''
    if fetch:
        force_owl_download = '--force_owl_download '
    owlnets_script: str = (f"{owlnets_script_py} "
                           f"--ignore_owl_md5 "
                           # f"--clean "
                           # f"--verbose "
                           f"{force_owl_download}"
                           # f"--with_imports "
                           f"--owlnets_dir {sab_jkg_dir} "
                           f"--owltools_dir {owltools_dir} "
                           f"--owl_dir {sab_source_dir} "
                           f" {owl_url} {sab}")
    ulog.print_and_logger_info(f"Running translator: {owlnets_script}")
    usub.call_subprocess(owlnets_script)

    # Run post-processing script.
    # April 2026 This appears to no longer be necessary.
    #owlnets_dir: str = os.path.join(sab_jkg_dir, sab)
    #fix_owlnets_metadata_file(repo_root=repo_root,
                              #ulog=ulog,
                              #owlnets_dir=owlnets_dir,
                              #cfg=cfg)

def main():

    # Locate the root directory of the repository for absolute
    # file paths.
    repo_root = find_repo_root()
    log_dir = os.path.join(repo_root, 'generation_framework/builds/logs')
    # Set up centralized logging.
    ulog = ubkgLogging(log_dir=log_dir, log_file='sab2edgenode.log')
    ulog.print_and_logger_info('-' * 50)

    # Obtain command line arguments.
    args = get_args()
    ulog.print_and_logger_info('Command line arguments:')
    sab_names = [s.upper() for s in args.sabs]
    ulog.print_and_logger_info(f' - SABs: {', '.join(sab_names)}')
    ulog.print_and_logger_info(f' - fetch fresh copies: {args.fetch}')

    # Obtain application configuration.
    cfg = ubkgConfigParser(path='ubkgjkg.ini', ulog=ulog)

    # Read and validate the file of SAB-specific configuration.
    usource = ubkgSources(ulog=ulog, cfg=cfg, repo_root=repo_root)

    # Process SABs.
    start_time = time.time()
    ulog.print_and_logger_info('-' * 50)
    ulog.print_and_logger_info(f"Translating SABs: {', '.join(sab_names)}")

    # For each SAB, execute the associated ETL subprocess.
    for sab_name in sab_names:

        ulog.print_and_logger_info(f"SAB: {sab_name}")
        source_type = usource.get(sab=sab_name, key='source_type')

        # Obtain absolute paths in repo to which to store:
        # - source files for the SAB
        # - converted files for the SAB
        sab_source_dir = os.path.join(repo_root, cfg.get_value(section='directories', key='sab_source_dir'))
        sab_jkg_dir = os.path.join(repo_root, cfg.get_value(section='directories', key='sab_jkg_dir'))

        if source_type == 'owl':
            if args.fetch:
                ulog.print_and_logger_info(f'Running translator: PhenKnowLator.')
                ulog.print_and_logger_info('The log file name is: phenKnowLator.log')

            # Use PheKnowLator to convert OWL files to OWLNETS files.
            run_pheknowlator_for_sab(cfg=cfg,
                                     ulog=ulog,
                                     sab_source_dir=sab_source_dir,
                                     sab_jkg_dir=sab_jkg_dir,
                                     sab_json=usource.sab_json,
                                     sab=sab_name,
                                     repo_root=repo_root,
                                     fetch=args.fetch)

        else:

            # Pass the value of the --fetchnew argument to the subprocess.
            farg = ''
            if args.fetch:
                farg = '--fetchnew'

            script = f'{usource.get(sab=sab_name, key='execute')}'
            ulog.print_and_logger_info(f"Running translator: {script}")
            ulog.print_and_logger_info(f"The log file shares the script name.")
            usub.call_subprocess(script)

        # Add log entry for how long it took to do the processing...
        elapsed_time = time.time() - start_time
        ulog.print_and_logger_info(f'Translation completed. Total Elapsed time: {"{:0>8}".format(str(timedelta(seconds=elapsed_time)))}')


if __name__ == "__main__":
    main()